feat: add translations
tametsi/ligas pull request #14
Opened 2023-03-24 22:57 UTC by xXjojaXx

closes #11

2023-03-27 09:33 UTC, tametsi commented on src/components/layout/Sidebar.svelte
> +	import { link } from 'svelte-spa-router';
remove unused imports from `svelte-spa-router`

2023-03-27 09:47 UTC, tametsi commented on src/components/pages/Analytics.svelte
> +			(_v, i) => `${get(_)('analytics.round')}: ${i + 1}`
use `$` instead of `get`

2023-03-27 10:07 UTC, tametsi commented on src/components/pages/Edit.svelte
> +					>{$_('edit.add_runner')}
style: whitespace consistency

2023-03-27 10:51 UTC, tametsi commented on src/lang/de.ts
> +			'von Rundenzeiten während einem Wettkampf zu erleichtern.',
der dativ ist dem genitiv sein tod

2023-03-28 09:52 UTC, tametsi commented on src/lib/run.ts
> +			`${get(_)('runner.stats.rounds')} (Format: mm:ss:ff)`,
looks like `in`and `Format` are international words now...

2023-03-28 10:30 UTC, tametsi commented on src/components/elements/HistoryEntry.svelte
>  				title="Loads this session. This session will be modified."
missing translations for `title`

2023-03-29 06:00 UTC, tametsi requested changes
pls resolve the comments I left  
and add translations for this line: https://github.com/tametsi/ligas/blob/46e3649bda7b44fa6d419ffa53f49b9116c03858/src/components/layout/Navbar.svelte#L15

2023-03-29 07:43 UTC, xXjojaXx commented
All comments of the review should be resolved by the two commits above.
Please inspect the new changes again before merging the pull request.
享受翻译的乐趣！

2023-03-29 08:43 UTC, tametsi approved these changes

2023-03-29 08:51 UTC, merged